default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: airflowuser
      pass: pssd
      port: 5432
      dbname: airflowdb
      schema: dbt
      threads: 4