version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pssd
      POSTGRES_USER : airflowuser
      POSTGRES_DB : airflowdb
      DBT_SCHEMA: dbt
      DBT_SEED_SCHEMA: dbt_seed_data
      AIRFLOW_SCHEMA: airflow
    expose:
      - "5432"
    restart: always
    volumes:
      - ./scripts_postgres:/docker-entrypoint-initdb.d
      - ./dbt:/dbt

  airflow:
    build: .
    restart: always
    environment: 
      DBT_PROFILES_DIR: /dbt
      AIRFLOW_HOME: /airflow
      AIRFLOW__CORE__DAGS_FOLDER: /airflow/dags
      # Postgres details need to match values defined in the postgres service
      POSTGRES_USER: airflowuser
      POSTGRES_PASSWORD: pssd
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: airflowdb
    depends_on:
      - "postgres"
    ports:
      - "8000:8080"
    volumes:
      - ./dbt:/dbt
      - ./airflow:/airflow

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - "postgres"

